### ISSUE TITLE
Advanced Maps, calling a single node causes a huge array of one Gateway ID in POST data

### ISSUE THREAD

**Issue by Waldmensch1** [ttnmapper/bugtracker#10]
Hi,

I see a funny behavior in Post request in common.js 217ff

to reproduce:
- type in a valid device
- set Picker to today

Don't think it is needed to put the same or 2  gateway ID's 200 times into POST data?! See screenshot

![image](https://user-images.githubusercontent.com/57328533/91905239-84811600-eca6-11ea-837f-206aeb9683c6.png)

**Comment by jpmeijers** [comment]
I can reproduce this. Likely a bug where the gateway is requested for every mapped point. Some deduplication needs to be done.

**Comment by jpmeijers** [comment]
I believe this was fixed a while back, so closing the issue now. In case you see it popping up again, please let me know.
