### ISSUE TITLE
data not making it to final map, although advanced maps shows everything got tracked

### ISSUE THREAD

**Issue by flashfingaz** [ttnmapper/bugtracker#11]
referring to this csv data:

https://ttnmapper.org/devices/csv.php?device=ffgz_mapper_42&startdate=2021-03-10&enddate=2021-03-12&gateways=on&lines=on&points=on

and this advanced map:
https://ttnmapper.org/devices/?device=ffgz_mapper_42&startdate=2021-03-12&enddate=2021-03-12&gateways=on&lines=on&points=on

data seems okay but it seems not to make its way onto the final map:
- id 288791678 has HDOP of 0.9 and is part of a trail that is not yet on the map
CSV data: 288791678, 2021-03-12 13:18:41, ffgz_mapper_42, unhb_de-mapper, 58A0CBFFFE800E14, LORA, SF7BW125, 10.50, -91.00, 868.100, 225, 51.533247, 7.647032, 88.0, 0.00, 0.9, 8, hdop, http-ttnmapper/2.7.1
- id 288782005 has HDOp of 1.2 and was received by a brand new gw (this was actually reason of the ride, to make owner happy) but also not on map
CSV data: 288782005, 2021-03-12 12:52:50, ffgz_mapper_42, unhb_de-mapper, 313330370F003C00, LORA, SF7BW125, 4.25, -84.00, 867.500, 70, 51.555145, 7.687394, 66.0, 0.00, 1.2, 8, hdop, http-ttnmapper/2.7.1

first i thought it's due to the missing location accuracy, then realized that nodes are sending hdop. not sure what else might be the problem. intake delay also seems out of question as this data is 2 days old now. maybe these nodes get filtered because they rund 24/7 and add too much to the db?

anyways, would be grateful for some help - ttnmapper gives us a great insight on the lora coverage in our community. this is even more important these days as the city discovered lorawan and it seems like they want to deploy a closed infrastructure. showing them that we already have good ttn coverage with only a few gateways (number currently increasing) will hopefully make an positive impact

**Comment by flashfingaz** [comment]
would really be great to get some insight into this. maybe this is expected, maybe its a bug. currently i have very mixed feelings about this. i love the project, but i'm not sure if i'm still adding value by taking tracker nodes with me or i just add noise

**Comment by jpmeijers** [comment]
@flashfingaz sorry for the frustration. With the entire migration to TTN v3, things are a little in limbo.

For now as long as you can see your data on the per-device raw data map, all is fine. Getting it to display on the main map is a little difficult as there are many steps with dependencies on not-yet-available APIs. I'm trying to add what I can when I have time, but unfortunately this remains a hobby project which I can only work on in non-business hours. I hope you understand.

Please continue mapping. Your data is not lost, it's just taking some time to be processed and displayed on the main map.

**Comment by flashfingaz** [comment]
hey @jpmeijers ! thanks for the update, knowing that there is nothing wrong on my side makes a big difference for me! 
and please be assured there is no demand from my side, i completely understand you are doing this in your spare time. my fear was that due to the nodes sending constantly I would be somehow doing harm to the project and therefore maybe the nodes would be filtered or something like that.

so i will just wait until the data eventually got digested into the main map and continue mapping :)

**Comment by jpmeijers** [comment]
The current main map is a heatmap of the coverage. The way this layer is generated allows us to add new data almost in realtime. Because this issue refers to the old radar plots main map, I am closing it now.
