### ISSUE TITLE
Missing integration of V3 devices

### ISSUE THREAD

**Issue by racsnet** [ttnmapper/bugtracker#12]
Hello there,

Following https://github.com/ttnmapper/documentation/blob/master/integration/tts-integration-v3.md points to a Webhook Template for TTNMapper. But this template does not exist in my The Things Network V3 console. 

Are there informations available to create a custom webhook?

**Comment by jpmeijers** [comment]
It's a catch-22 situation. I had to write documentation how the webhook template works before TTI will accept the new template.

Template was merge a week or so ago:
https://github.com/TheThingsNetwork/lorawan-webhook-templates/pull/21

But TTI still needs to re-deploy the networks to refresh the list of available webhook templates. I however see they have maintenance scheduled for 12 April, so hopefully the new template will be available after that.
https://status.thethings.network/incidents/scclk8gydjyk

**Comment by racsnet** [comment]
Thanks for your reply.
Fingers crossed for 12 April :)

**Comment by racsnet** [comment]
Integration in v3 is now available
