### ISSUE TITLE
chirpstack: empty csv dump

### ISSUE THREAD

**Issue by lrswss** [ttnmapper/bugtracker#15]
Although there are entries on the map for an experiment with a chirpstack server, the csv dump of the same experiment is always empty:

<img width="400" alt="chirpstack_expirment_nodes" src="https://user-images.githubusercontent.com/33193763/142729569-591bff1b-1989-4ce7-b279-9848c8489016.png">

<img width="600" alt="chirptack_empty_csv_dump" src="https://user-images.githubusercontent.com/33193763/142729572-d7b8a535-e910-4feb-a44c-89643626805d.png">

**Comment by jpmeijers** [comment]
Thanks for reporting the two issues. Both were regressions introduced a while back. Both fixed now.
