### ISSUE TITLE
Could you install Japanese fonts ?

### ISSUE THREAD

**Issue by nishida1981** [ttnmapper/bugtracker#20]
There is only blocks in Japan in ttnmapper.
Could you install fonts in ttnmapper server ?
For example, mplus font may be useful.
[https://mplusfonts.github.io/](url)
Attached image is near Tokyo station.
![Screenshot_20231210-223511](https://github.com/ttnmapper/bugtracker/assets/153438344/a254edf1-89ae-4209-8bc6-a7c59924cb27)

**Comment by jpmeijers** [comment]
Swapped from the SkyLab OSM server to the global OSM server solved this problem
![image](https://github.com/ttnmapper/bugtracker/assets/948278/54d4dc62-f410-4be2-a04d-cf8f497eac10)
