### ISSUE TITLE
Removal of old data in Heatmap

### ISSUE THREAD

**Issue by d70-t** [ttnmapper/bugtracker#5]
When a gateway is moved or goes offline, the heatmap should be updated as well. Otherwise situations like the following can happen:
![grafik](https://user-images.githubusercontent.com/6574622/43167090-d1c74dac-8f98-11e8-9d98-e70928cbf3bb.png)
(this it approximately at: 48.1556 N, 11.5384 E)

This might also affect the planned architecture (#2) where the changed grid cell queue might need to get notified by the cron job.

**Comment by jpmeijers** [comment]
Yes, this is a known bug and the main reason for the heat map feature still being BETA. It is not easy to fix this without causing a lot of extra processing. This will indeed need to be taken into account in the new architecture.

**Comment by jpmeijers** [comment]
https://github.com/ttnmapper/tile-map-server/commit/667d33b398d2e21df9dea61fb0db4a6f2cfe9184 has addressed this issue.
